Repository cpp-linter/clang-tools-pip, pull requests merged in 2022-08, with the labels that each got.

#14 Support setuptools_scm
  .gitignore
  setup.py
Labels: enhancement

#16 Pro revision
  .coveragerc
  .github/workflows/python-publish.yml
  .github/workflows/python-test.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  README.rst
  clang_tools/__init__.py
  clang_tools/install.py
  clang_tools/main.py
  clang_tools/util.py
  docs/Makefile
  docs/_static/extra_css.css
  docs/_static/favicon.ico
  docs/_static/logo.png
  docs/api.rst
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/requirements.txt
  pyproject.toml
  setup.py
  tests/test_install.py
  tests/test_main.py
  tests/test_util.py
Labels: documentation, enhancement

#17 Update readme and format code
  .github/workflows/python-publish.yml
  .github/workflows/python-test.yml
  .pre-commit-config.yaml
  README.rst
Labels: documentation

#22 Fix force overwriting symlink issue (#20)
  .gitignore
  clang_tools/install.py
  tests/test_install.py
Labels: bug

#25 verify pre-existing binaries' SHA512
  .gitignore
  README.rst
  clang_tools/install.py
  clang_tools/util.py
  docs/_static/extra_css.css
  tests/clang-query-12_linux-amd64.sha512sum
  tests/clang-query-12_macosx-amd64.sha512sum
  tests/clang-query-12_windows-amd64.sha512sum
  tests/test_util.py
Labels: enhancement

#29 add no-progress-bar and uninstall CLI options
  .coveragerc
  .gitignore
  README.rst
  clang_tools/install.py
  clang_tools/main.py
  clang_tools/util.py
  docs/_static/favicon.ico
  docs/_static/logo.png
  docs/_static/new_favicon.ico
  docs/conf.py
  docs/index.rst
  pyproject.toml
  requirements-dev.txt
  tests/test_install.py
  tests/test_main.py
  tests/test_util.py
Labels: enhancement

#31 Change to uppercase then reproduce #30
  clang_tools/install.py
Labels: documentation
